spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        envers:
          audit_table_suffix: _AUD
          revision_field_name: REV
          revision_type_field_name: REVTYPE

  liquibase:
    drop-first: false
    change-log: classpath:db/changelog/db-changelog-master.yml
    contexts: migrated

server:
  port: 9090